### ISSUE TITLE
[Clarification] Drag Ruler Version

### ISSUE THREAD

**Issue by NuptupTDOW** [Valerionn/foundry-dragruler-pf2e#2]
Should this module be used in conjunction with the posted Drag Ruler, or with your forked version of Drag Ruler?

**Comment by Valerionn** [comment]
Hey! It's possible with both, but my forked version fixes two bugs: [#337](https://github.com/manuelVo/foundryvtt-drag-ruler/issues/337) and [#342](https://github.com/manuelVo/foundryvtt-drag-ruler/issues/342).

Therefore, I would recommend using my forked version ([instructions here](https://github.com/manuelVo/foundryvtt-drag-ruler/pull/343#issuecomment-2343528027)), which is also what I use in my own games.
